### ISSUE TITLE
update pydantic

### ISSUE THREAD

**Issue by StanNaumenko** [opendatadiscovery/odd-cli#5]
We need to update loguru to the version "^0.7.2"

Thus, the odd-dbt has been updated as well. However, the pydantic version has been updated automatically and odd-dbt cannot be run with the latest version.

The following error can be seen when running the tests

> Traceback (most recent call last):
  File "/home/linuxbrew/.linuxbrew/Cellar/python@3.11/3.11.7_1/lib/python3.11/unittest/loader.py", line 162, in loadTestsFromName
    module = __import__(module_name)
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/stanislav/gen_ai_odd/odd-cli/tests/test_collect.py", line 8, in <module>
    from odd_cli.main import app
  File "/home/stanislav/gen_ai_odd/odd-cli/odd_cli/main.py", line 3, in <module>
    from odd_dbt.app import app as dbt_test_app
  File "/home/stanislav/.cache/pypoetry/virtualenvs/odd-cli-0kdtE6m1-py3.11/lib/python3.11/site-packages/odd_dbt/app.py", line 9, in <module>
    from odd_dbt import config
  File "/home/stanislav/.cache/pypoetry/virtualenvs/odd-cli-0kdtE6m1-py3.11/lib/python3.11/site-packages/odd_dbt/config.py", line 2, in <module>
    from pydantic import BaseSettings
  File "/home/stanislav/.cache/pypoetry/virtualenvs/odd-cli-0kdtE6m1-py3.11/lib/python3.11/site-packages/pydantic/__init__.py", line 386, in __getattr__
    return _getattr_migration(attr_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/stanislav/.cache/pypoetry/virtualenvs/odd-cli-0kdtE6m1-py3.11/lib/python3.11/site-packages/pydantic/_migration.py", line 296, in wrapper
    raise PydanticImportError(
pydantic.errors.PydanticImportError: `BaseSettings` has been moved to the `pydantic-settings` package. See https://docs.pydantic.dev/2.7/migration/#basesettings-has-moved-to-pydantic-settings for more details.

For further information visit https://errors.pydantic.dev/2.7/u/import-error

**Comment by ValeriyWorld** [comment]
Closed with https://github.com/opendatadiscovery/odd-dbt/pull/15 and #7
